fieldLayouts:
  63afac0d-f453-470f-9777-f7244fdc4556:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-05T18:42:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 14a45045-72c1-4c83-adc7-4a45d6c4bc41
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ec646b04-3381-4584-85b1-d87c11531a9c
        userCondition: null
handle: keywords
name: Keywords
