defaultPlacement: end
fieldLayouts:
  25ae0199-bb85-4be9-877f-d5aeb08b88d2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-04T23:38:49+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: b874c306-a9b7-4db8-a1a0-f11f828a7aa6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d2bbfbf9-c0c4-4a65-a8db-719ff2c6eebf
        userCondition: null
handle: genre
name: Genre
siteSettings:
  86baf7e9-fa04-4917-bea7-e40ea7b944ba: # Stuff Your Kindle: Crime Edition
    hasUrls: true
    template: genre/_category.twig
    uriFormat: 'genre/{slug}'
structure:
  maxLevels: null
  uid: 9f77a722-cbbc-4612-bd45-e97cb39e67ad
