defaultPlacement: end
fieldLayouts:
  cba2f5cc-06f1-4f09-b6f3-b2703c0a4f39:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-12T20:19:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 8f57fde9-6557-46fe-aa94-2df535b9ef58
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8b8d7fbb-dc73-4a65-927b-9650efb2670d
        userCondition: null
handle: romance
name: Romance
siteSettings:
  86baf7e9-fa04-4917-bea7-e40ea7b944ba: # Stuff Your Kindle: Crime Edition
    hasUrls: true
    template: genre/_category.twig
    uriFormat: 'genre/{slug}'
structure:
  maxLevels: null
  uid: b5f7c766-f902-4cd9-845a-8f58f9735532
