baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Stuff Your Kindle with Crime'
primary: true
siteGroup: 37614ce4-9525-41ed-ba51-8fb272adfda6 # Stuff Your Kindle: Crime
sortOrder: 1
