altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  e9f6b41b-5894-4ecd-a2c0-68215f124fba:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-05T20:06:40+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: aee172f3-5b5d-4b93-bf06-3bf804317342
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b8b0068a-9191-407a-934a-fd416f8faccd
        userCondition: null
fs: images
handle: bookCovers
name: 'Book Covers'
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
