altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  76abe164-2c2a-4636-a850-69cf1a34dfcb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-18T00:13:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 1e965ce2-03e9-430b-b6f0-43681834268d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0d6099dc-7377-4fd5-b6c0-b71cf6144abd
        userCondition: null
fs: feeds
handle: feedsVolume
name: 'Feeds Volume'
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
