columnSuffix: null
handle: body
instructions: null
name: Body
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  css: null
  cssFile: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  entryTypes:
    - 46b76175-241b-4807-a8d1-f474d60252b1 # Singles
  fullGraphqlData: false
  headingLevels:
    - 2
    - 3
  js: null
  jsFile: null
  options: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  toolbar:
    - heading
    - '|'
    - bold
    - italic
    - underline
    - strikethrough
    - bulletedList
    - numberedList
    - '|'
    - insertImage
    - '|'
    - link
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
