columnSuffix: null
handle: eventDetails
instructions: null
name: 'Event Details'
searchable: false
settings:
  default: true
  offLabel: Hide
  onLabel: Show
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
