columnSuffix: null
handle: explicit
instructions: null
name: 'Includes Explicit Content?'
searchable: false
settings:
  default: true
  offLabel: 'No'
  onLabel: 'Yes'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
