columnSuffix: null
handle: genre
instructions: null
name: Genre
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 1
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: true
  source: 'group:789523c3-d71a-4be3-b0a0-5a0d2462abe1' # Genre
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
