columnSuffix: null
handle: keywords
instructions: null
name: Keywords
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add a keyword'
  showCardsInGrid: false
  showSiteMenu: false
  source: 'taggroup:ab9df739-9a0c-41b9-938d-e282b83861e4' # Keywords
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Tags
