columnSuffix: null
handle: shortRead
instructions: null
name: 'Short Read'
searchable: false
settings:
  default: false
  offLabel: 'Long read'
  onLabel: 'Short Read'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
