dateModified: 1745103723
email:
  fromEmail: andrew@circa42.com
  fromName: 'Stuff Your Kindle: Crime'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  feeds:
    hasUrls: false
    name: Feeds
    settings:
      path: $FEEDS_FOLDER
    type: craft\fs\Local
    url: $BASE_URL/feeds
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/images/covers'
    type: craft\fs\Local
    url: /images/covers
meta:
  __names__:
    1c31696e-f556-4d1b-902c-6a1df93843bb: Genre # Genre
    1de1c31f-1793-4a6c-ac70-1c5e7e2907a9: Thumb # Thumb
    1e32e33a-2e30-4288-9032-6f6dd47f2bbd: 'Store Links' # Store Links
    5ac2d28b-bcfe-4c01-84bd-7023c7f9fe3b: 'Book Entry' # Book Entry
    5bfe5019-ad3d-44a8-8baf-d4d6cd7ade2e: Description # Description
    6fd0f671-1f0a-4f7d-b765-5b1bf2d05c4d: 'Feed Upload' # Feed Upload
    7d5b5753-a092-4bca-bdf2-e62434abf683: 'Pen Name' # Pen Name
    8b19d58e-a22c-47c2-804f-f668498f2af1: Alerts # Alerts
    8e8d3d60-ef5a-4d0e-87ce-462056770daf: Alerts # Alerts
    17daa88c-2431-437f-8aad-f702d1cb5dd7: Hook # Hook
    45e385b2-61aa-459b-9af9-130ee578ed93: 'Romance Level' # Romance Level
    46b76175-241b-4807-a8d1-f474d60252b1: Singles # Singles
    72fd5fbf-d505-4d75-8a03-dbb4ac4d5fa4: Medium # Medium
    86baf7e9-fa04-4917-bea7-e40ea7b944ba: 'Stuff Your Kindle: Crime Edition' # Stuff Your Kindle: Crime Edition
    465bec08-62f6-42c8-812a-654ff208bb73: Embed # Embed
    603eddaf-1f01-40b9-bc37-b24146ec7fa2: Explicit # Explicit
    619ae31f-ba31-40ac-a935-ac7b965394cc: Simple # Simple
    690f8cf4-eb02-4552-a54b-d6bb5dcbd200: 'Store Link' # Store Link
    794f428d-3f9f-4bb1-8fd7-6ca003d7c247: Store # Store
    3822f532-6314-47bd-8921-3df165b3a52a: Body # Body
    7863d0f8-7a02-4d03-b291-e630ffccb754: Home # Home
    7905d83c-dbcd-4b4a-b792-36421f7e7c4e: 'Feeds Volume' # Feeds Volume
    8969caf3-731c-4802-bef4-8e422fdd0765: About # About
    37614ce4-9525-41ed-ba51-8fb272adfda6: 'Stuff Your Kindle: Crime' # Stuff Your Kindle: Crime
    789523c3-d71a-4be3-b0a0-5a0d2462abe1: Genre # Genre
    922578ca-b0b6-48c0-aae1-c55cd66e3ffd: 'Book Covers' # Book Covers
    18990190-5b61-459e-8e5c-7efd864289d0: 'Public Schema' # Public Schema
    63314730-9463-4027-81c8-c8a5ee186f19: 'Book Cover' # Book Cover
    aa93aced-56a4-4b94-8ffe-80e5cfe98f0a: Books # Books
    ab9df739-9a0c-41b9-938d-e282b83861e4: Keywords # Keywords
    b2ac142b-7068-464d-9a9f-89ffe30d6601: Home # Home
    b9390259-c651-4b5a-bf5e-f5a4659cc704: 'Explicit Categories' # Explicit Categories
    bd08465f-6b04-4419-8b44-f53ed8fd4767: Keywords # Keywords
    bd98f8d4-685e-4ff6-ba96-5a59af697eab: Romance # Romance
    d2e5aeee-67eb-427b-b509-1392eb5ed1d1: 'Author Name' # Author Name
    dd0271aa-2c8e-4ac9-af62-7b033f1f8550: Stores # Stores
    e6b43986-34b3-4dae-949d-8b28bbdf62fa: 'Includes Explicit Content?' # Includes Explicit Content?
    e398798c-c71d-49fd-9a2a-9f9f5e96e0fa: 'Store Entry' # Store Entry
    f0368cdb-4acc-4a12-9b6b-612a670fd2f1: Authors # Authors
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 5.1.1
  knock-knock:
    edition: standard
    enabled: false
    schemaVersion: 1.1.1
    settings:
      checkInvalidLogins: false
      enableCpProtection: false
      enabled: true
      forcedRedirect: ''
      invalidLoginWindowDuration: '3600'
      loginPath: ''
      maxInvalidLogins: 10
      password: 'syK:crime!'
      siteSettings:
        __assoc__:
          -
            - default
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - password
                  - ''
                -
                  - template
                  - ''
      template: ''
      useRemoteIp: false
system:
  edition: solo
  live: true
  name: 'Stuff Your Kindle: Crime'
  retryDuration: null
  schemaVersion: 5.7.0.3
  timeZone: America/Vancouver
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
