defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 46b76175-241b-4807-a8d1-f474d60252b1 # Singles
handle: about
maxAuthors: 1
name: About
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  86baf7e9-fa04-4917-bea7-e40ea7b944ba: # Stuff Your Kindle: Crime Edition
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry.twig
    uriFormat: '{slug}'
type: single
